apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wh-skills-external-secret
  namespace: whanci
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: wh-skills-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: wh/skills/secret
